### ISSUE TITLE
ImageTextStateDisplay NullPointerException

### ISSUE THREAD

**Issue by Supercaly** [tylersuehr7/empty-state-recyclerview#3]
When i create a new instace of the class in a fragment doing
```
ImageTextStateDisplay stateEmpty = new ImageTextStateDisplay(getContext(), R.drawable.ic_empty, "title", "sub");
```
i get

```java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                          at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:719)
                                                                          at com.tylersuehr.esr.ImageTextStateDisplay.configure(ImageTextStateDisplay.java:320)
                                                                          at com.tylersuehr.esr.ImageTextStateDisplay.drawTextFirst(ImageTextStateDisplay.java:256)
                                                                          at com.tylersuehr.esr.ImageTextStateDisplay.onDrawState(ImageTextStateDisplay.java:98)
                                                                          at com.tylersuehr.esr.EmptyStateRecyclerView.dispatchDraw(EmptyStateRecyclerView.java:68)
                                                                          at android.view.View.draw(View.java:19985)
                                                                          at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:4107)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18857)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.View.draw(View.java:19710)
                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:4321)
                                                                          at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1366)
                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4107)
                                                                          at android.view.View.draw(View.java:19985)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18857)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4305)
                                                                          at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4285)
                                                                          at android.view.View.updateDisplayListIfDirty(View.java:18817)
                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:673)
                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:679)
                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:787)
                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:3257)
                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3073)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2453)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1441)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7076)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:935)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:747)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:682)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:921)
                                                                          at android.os.Handler.handleCallback(Handler.java:819)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6656)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
03-21 15:39:56.823 10172-10172/com.supercaly.petify E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)```

**Comment by tylersuehr7** [comment]
Thanks for letting me know! Is this in the master or dev branch?

**Comment by tylersuehr7** [comment]
Alrighty, I think I fixed this issue. The problem was the BitmapFactory.decodeResource was returning null for when you try to decode a vector drawable. 

The fix just uses ContextCompat to load the drawable and then the drawableToBitmap() method to convert it for use
